### ISSUE TITLE
Unicode character formatting on keyboard layout pages

### ISSUE THREAD

**Issue by DJm00n** [MicrosoftDocs/globalization#256] opened 2023-06-20 14:32 UTC
Single characters on popups should be formatted **ALL UPPPERCASE** as per [4.8 Name. Unicode Standard](https://www.unicode.org/versions/Unicode15.0.0/ch04.pdf) like this:
`U+1033F GOTHIC LETTER URUS`

Also, according to [UAX #34](https://unicode.org/reports/tr34/) character sequences should be formatted as "Unicode named character sequence" like this:
`<U+10339, U+0308> GOTHIC LETTER EIS WITH COMBINING DIAERESIS`

>names for named character sequences are constructed by appending the names of the constituent elements together while eliding duplicate elements, and possibly introducing the words “WITH” or “AND” between elements for clarity

Can you make corresponding changes?

![image](https://github.com/MicrosoftDocs/globalization/assets/1285934/0d957d9f-f0c1-4228-b6f5-d3ac673379a5)

**Comment by DJm00n** [comment] 2023-06-20 14:32
@jowilco

**Comment by jowilco** [comment] 2023-06-22 23:50
@DJm00n I've fixed the title case -> upper case issue. Reformatting the ligature descriptions with "WITH" will take a little longer.

**Comment by jowilco** [comment] 2023-06-23 16:50
@DJm00n After thinking about it a little more, I'm not sure that <U+XXXX, U+YYYY> XXXXXXXXXXX [WITH/AND] YYYYYYYYY is the correct approach here. While some ligatures are "letter + combining character" (not accurate, but I think that you'll understand what I am getting at), other ligatures are simply combinations or groups of characters. I went with:
<U+XXXX, U+YYYY> XXXXXXXXXXX, YYYYYYYYY

**Comment by DJm00n** [comment] 2023-06-29 11:41
@jowilco I understand you objection concerning [WITH/AND] but I think current `U+09B0, U+09CD BENGALI LETTER RA, BENGALI SIGN VIRAMA` format is not readable.

Possible alternative would be `<U+09B0 BENGALI LETTER RA, U+09CD BENGALI SIGN VIRAMA>`

`<>` is mandatory here since it means sequences of code points.

**Comment by DJm00n** [comment] 2023-06-29 11:57
Also, it would be great if you can add `VK_` codes on the button popups. It is mandatory for a user to see which VK is emitted on a key press too (think about QWERTY vs AZERTY vs DVORAK_R etc keyboards) - and this value is not clear for non-ASCII keyboards at all.

**Comment by DJm00n** [comment] 2023-06-29 13:24
Also, it would be great if you can add character codes for the VK_SPACE (usually `U+0020 SPACE`), VK_RETURN (usually `U+000D CARRIAGE RETURN (CR)`), VK_BACK (usually `U+0008 BACKSPACE`), VK_TAB (usually `U+0009 CHARACTER TABULATION`) keys in all shift states.

**Comment by jowilco** [comment] 2023-07-07 15:39
@DJm00n  - Please try now. I hope that is closer.

**Comment by DJm00n** [comment] 2023-07-07 17:55
@jowilco now it looks much better! thank you!

one thing I noted that `<>` is rendered for non-BMP Unicode chars. See https://learn.microsoft.com/en-us/globalization/keyboards/kbdgthc for example.

**Comment by jowilco** [comment] 2023-07-07 18:34
@DJm00n - Good catch. Fixed now.

Justy FYI: Internally, ligatures are stored in the same way as the non-BMP characters. The non-BMP characters have to be converted from surrogate pairs, while the ligatures are just combinations of characters.

**Comment by DJm00n** [comment] 2023-07-07 22:44
Thank you again, @jowilco!

**Comment by DJm00n** [comment] 2023-07-19 10:35
Hi @jowilco!
Minor nit. There SHOULD BE `<>` in this case with surrogate + ligature:
![image](https://github.com/MicrosoftDocs/globalization/assets/1285934/2648dd9e-7d59-4293-9b17-7d591aa022e0)

**Comment by jowilco** [comment] 2023-07-20 19:28
Thanks @DJm00n - good catch!
Fortunately, this was the only instance.
https://github.com/MicrosoftDocs/globalization/pull/267

**Comment by DJm00n** [comment] 2023-07-20 20:18
@jowilco thank you for a quick fix!

**Comment by DJm00n** [comment] 2023-11-09 11:41
Hi @jowilco!

Dead Key characters are missing Unicode character names:
![image](https://github.com/MicrosoftDocs/globalization/assets/1285934/7d987f92-e1ab-4288-bfe4-692d6f81cc6c)

Minor: also, there should be space after `:` char (not before) in `DeadKey :^ â Â ê Ê î Î ô Ô û Û` string.

**Comment by jowilco** [comment] 2023-11-09 22:30
Hi @DJm00n - Good to hear from you!

Good suggestions. Implemented in https://github.com/MicrosoftDocs/globalization/pull/281

**Comment by DJm00n** [comment] 2023-11-11 07:32
Thank you, @jowilco!

Here is name of character is still missing:
<img width="811" alt="image" src="https://github.com/MicrosoftDocs/globalization/assets/1285934/cf00b0d0-8ea6-4130-a7b4-fc2de895524c">

**Comment by DJm00n** [comment] 2023-11-11 07:41
Also, it seems some keyboards can output chars/deadchars from the Private Use Area (range: E000—F8FF).
But current implementation just omits them.

For example ADLaM layout have such keys in Ctrl+Alt and Shift+Ctrl+Alt modes and on GRAVE ACCENT deadkey:
<img width="751" alt="image" src="https://github.com/MicrosoftDocs/globalization/assets/1285934/346ee65f-760f-4544-9248-4f34bacf4dae">
https://learn.microsoft.com/en-us/globalization/keyboards/kbdadlm
https://kbdlayout.info/kbdadlm

Maybe you can output them too? Something like `U+EF1E Private Use Area`?

**Comment by jowilco** [comment] 2023-11-20 22:31
@DJm00n - Thanks again for finding the issues. I really do appreciate that you are willing to help us make the information that we are publishing better!

I added the character names to the Deadkey base characters.
The issue with Osage and ADLaM is that they were set as keyboards that didn't support AltGr, which of course they do. Once they were set correctly, the PUA characters appeared correctly.

**Comment by DJm00n** [comment] 2023-11-20 22:54
>The issue with Osage and ADLaM is that they were set as keyboards that didn't support AltGr, which of course they do

How do you set that? It can be detected by `KLLF_ALTGR` flag in low word of `KBDTABLES.fLocaleFlags` if I got it right.

**Comment by jowilco** [comment] 2023-11-20 23:00
That would be a better way of doing this. Unfortunately, all of the changes that I have been making are to a tool that I inherited that is solely for generating the keyboards for this site. It relies on a static database table with records for each keyboard. I really should remove that dependency and instead generate the data when I generate the keyboards, but that will take time/resources.

For the ADLaM keyboard, it isn't a dead key. If you use the AltGr key, you'll see the PUA chars on VK_OEM_3 and several others.

**Comment by DJm00n** [comment] 2023-11-20 23:04
VK_OEM3 without shift states is a deadkey according to https://kbdlayout.info/kbdadlm/download/klc

```
DEADKEY	0060	// GRAVE ACCENT

0042	ef1e	// B -> 
004a	ef1f	// J -> 
004b	ef1d	// K -> 
0050	ef20	// P -> 
0053	ef21	// S -> 
0056	ef1c	// V -> 
0062	ef40	// b -> 
006a	ef41	// j -> 
006b	ef3f	// k -> 
0070	ef42	// p -> 
0073	ef43	// s -> 
0076	ef3e	// v -> 
0060	0060	// ` -> `
```

**Comment by DJm00n** [comment] 2023-11-20 23:10
>It relies on a static database table with records for each keyboard

Oh, thats sad. I had a related question - how to detect [physical keyboard layout type](https://commons.wikimedia.org/wiki/File:Physical_keyboard_layouts_comparison_ANSI_ISO_ABNT.png) from `KBDTABLES`....and it seems now answer is "there is no way". Right?

**Comment by jowilco** [comment] 2023-11-20 23:18
The KLC doesn't always correctly reflect what the keyboard is returning. The keyboard layout generator used to depend on KLC, but we found some issues with the .klc files that are generated, so we now use user32.dll directly (https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-tounicodeex, https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeyboardlayoutlist, etc.)

Let me spend some more time with this when I have more time available.

>>>Oh, thats sad.
It solved an issue at the time...

>>>how to detect physical keyboard layout type 
I don't believe that the keyboard driver knows anything about the keyboard itself.

**Comment by jowilco** [comment] 2023-12-22 14:38
Hi @DJm00n - I had some time to look at the ADLaM issue again. I installed the keyboard on Windows 11 and tried using the ` deadkey. It appears that it can be used with any character, not just the set mentioned at the bottom of the page on https://kbdlayout.info/kbdadlm/shiftstates. Unfortunately, there is very little information on the Internet about using the ADLaM keyboard, at least in English, so I'm not sure if this is an issue with the keyboard driver or if this is by design.

I don't think that it is worth listing every single character in the ` tooltip, but I am open to suggestions.

If nothing else, I plan on updating the PUA keys (AltGr) to display the correct glyphs. I was also thinking about adding the base character to each of the deadkey combinations in the tooltip.

Happy holidays!

**Closed** 2024-03-18 15:21 UTC
