### ISSUE TITLE
Some topics are not hooked up to the TOC

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/globalization#53] opened 2018-01-08 23:53 UTC
By design?

For example: https://docs.microsoft.com/en-us/globalization/input/input

But then you have https://docs.microsoft.com/en-us/globalization/input/text-input which is associated with 2 entries in the TOC

They also tend to be the ones without the mandatory metadata header section

**Comment by jotasprout** [comment] 2018-10-08 20:31
@mairaw Asked if this was by design. If it isn't, I can start to fill in the gaps by working on her first example and searching for others. Her second example is definitely not consistent with other sections so I'll fix that one then move on to others like the first.

**Comment by jotasprout** [comment] 2018-10-08 21:27
On the [https://docs.microsoft.com/en-us/globalization/input/input](https://docs.microsoft.com/en-us/globalization/input/input) page, at least one of the links on the page go to the wrong location (it goes to a page that is linked in the TOC but not listed) so I'm definitely taking a close look at everything.

**Comment by Paul-Dempsey** [comment] 2020-04-22 20:30
re: "Whom could I ask": that would be Jan Nelson in GRE

**Comment by jowilco** [comment] 2020-08-10 15:13
Per discussion with @mairaw, closing as could no longer reproduce.

**Closed by jowilco** 2020-08-10 15:13 UTC
